-- -------------------------------------------------------------
--
-- Module: filterDesigner
-- Generated by MATLAB(R) 9.14 and Filter Design HDL Coder 3.1.13.
-- Generated on: 2024-03-01 10:21:19
-- -------------------------------------------------------------

-- -------------------------------------------------------------
-- HDL Code Generation Options:
--
-- TargetLanguage: VHDL
-- TargetDirectory: C:\Users\ap2650j\OneDrive - University of Greenwich\VHDL\Audio
-- Name: filterDesigner
-- TestBenchStimulus: impulse step ramp chirp noise 

-- -------------------------------------------------------------
-- HDL Implementation    : Fully parallel
-- Folding Factor        : 1
-- -------------------------------------------------------------
-- Filter Settings:
--
-- Discrete-Time FIR Filter (real)
-- -------------------------------
-- Filter Structure  : Direct-Form FIR
-- Filter Length     : 201
-- Stable            : Yes
-- Linear Phase      : Yes (Type 1)
-- -------------------------------------------------------------



LIBRARY IEEE;
USE IEEE.std_logic_1164.all;
USE IEEE.numeric_std.ALL;

ENTITY filterDesigner IS
   PORT( clk                             :   IN    std_logic; 
         clk_enable                      :   IN    std_logic; 
         reset                           :   IN    std_logic; 
         filter_in                       :   IN    real; -- double
         filter_out                      :   OUT   real  -- double
         );

END filterDesigner;


----------------------------------------------------------------
--Module Architecture: filterDesigner
----------------------------------------------------------------
ARCHITECTURE rtl OF filterDesigner IS
  -- Local Functions
  -- Type Definitions
  TYPE delay_pipeline_type IS ARRAY (NATURAL range <>) OF real; -- double
  -- Constants
  CONSTANT coeff1                         : real := 3.4424189839880881E-04; -- double
  CONSTANT coeff2                         : real := -8.9204858579275967E-04; -- double
  CONSTANT coeff3                         : real := -2.2025231045459236E-03; -- double
  CONSTANT coeff4                         : real := -3.3311967217403678E-03; -- double
  CONSTANT coeff5                         : real := -4.0519399355335595E-03; -- double
  CONSTANT coeff6                         : real := -4.2136243650270667E-03; -- double
  CONSTANT coeff7                         : real := -3.7715841910819022E-03; -- double
  CONSTANT coeff8                         : real := -2.7989027828169135E-03; -- double
  CONSTANT coeff9                         : real := -1.4748383764726239E-03; -- double
  CONSTANT coeff10                        : real := -5.2121091202658914E-05; -- double
  CONSTANT coeff11                        : real := 1.1909642541081957E-03; -- double
  CONSTANT coeff12                        : real := 2.0046726876392241E-03; -- double
  CONSTANT coeff13                        : real := 2.2176071268367680E-03; -- double
  CONSTANT coeff14                        : real := 1.7723634652808443E-03; -- double
  CONSTANT coeff15                        : real := 7.3967119962025448E-04; -- double
  CONSTANT coeff16                        : real := -6.9227834862994192E-04; -- double
  CONSTANT coeff17                        : real := -2.2518443082332504E-03; -- double
  CONSTANT coeff18                        : real := -3.6352071434542907E-03; -- double
  CONSTANT coeff19                        : real := -4.5652814102443177E-03; -- double
  CONSTANT coeff20                        : real := -4.8469114634968231E-03; -- double
  CONSTANT coeff21                        : real := -4.4074270615698128E-03; -- double
  CONSTANT coeff22                        : real := -3.3142196638273756E-03; -- double
  CONSTANT coeff23                        : real := -1.7652821280141869E-03; -- double
  CONSTANT coeff24                        : real := -5.3841894088120829E-05; -- double
  CONSTANT coeff25                        : real := 1.4866789005439521E-03; -- double
  CONSTANT coeff26                        : real := 2.5471222690863424E-03; -- double
  CONSTANT coeff27                        : real := 2.9040937623714389E-03; -- double
  CONSTANT coeff28                        : real := 2.4663614308932120E-03; -- double
  CONSTANT coeff29                        : real := 1.2966302022281505E-03; -- double
  CONSTANT coeff30                        : real := -3.9628186259847400E-04; -- double
  CONSTANT coeff31                        : real := -2.2941888005472916E-03; -- double
  CONSTANT coeff32                        : real := -4.0288483506097945E-03; -- double
  CONSTANT coeff33                        : real := -5.2528844063507614E-03; -- double
  CONSTANT coeff34                        : real := -5.7087699577777432E-03; -- double
  CONSTANT coeff35                        : real := -5.2822943985271313E-03; -- double
  CONSTANT coeff36                        : real := -4.0295622826544853E-03; -- double
  CONSTANT coeff37                        : real := -2.1714099556521507E-03; -- double
  CONSTANT coeff38                        : real := -5.5305750134082332E-05; -- double
  CONSTANT coeff39                        : real := 1.9088437575590857E-03; -- double
  CONSTANT coeff40                        : real := 3.3272561150024058E-03; -- double
  CONSTANT coeff41                        : real := 3.9002938803194623E-03; -- double
  CONSTANT coeff42                        : real := 3.4846526317990423E-03; -- double
  CONSTANT coeff43                        : real := 2.1270097333804367E-03; -- double
  CONSTANT coeff44                        : real := 6.1571629011121859E-05; -- double
  CONSTANT coeff45                        : real := -2.3292552928086186E-03; -- double
  CONSTANT coeff46                        : real := -4.5846783292933548E-03; -- double
  CONSTANT coeff47                        : real := -6.2532559947046972E-03; -- double
  CONSTANT coeff48                        : real := -6.9820582925067308E-03; -- double
  CONSTANT coeff49                        : real := -6.5898759378009543E-03; -- double
  CONSTANT coeff50                        : real := -5.1095753082449902E-03; -- double
  CONSTANT coeff51                        : real := -2.7901487836302845E-03; -- double
  CONSTANT coeff52                        : real := -5.6496624397325032E-05; -- double
  CONSTANT coeff53                        : real := 2.5668771868283171E-03; -- double
  CONSTANT coeff54                        : real := 4.5548160761323857E-03; -- double
  CONSTANT coeff55                        : real := 5.4847365180753982E-03; -- double
  CONSTANT coeff56                        : real := 5.1241843972648542E-03; -- double
  CONSTANT coeff57                        : real := 3.4850002052213701E-03; -- double
  CONSTANT coeff58                        : real := 8.3210563195582022E-04; -- double
  CONSTANT coeff59                        : real := -2.3567933886536911E-03; -- double
  CONSTANT coeff60                        : real := -5.4749506577907543E-03; -- double
  CONSTANT coeff61                        : real := -7.8994828919364928E-03; -- double
  CONSTANT coeff62                        : real := -9.1128689950590331E-03; -- double
  CONSTANT coeff63                        : real := -8.8098827781718392E-03; -- double
  CONSTANT coeff64                        : real := -6.9685249545193059E-03; -- double
  CONSTANT coeff65                        : real := -3.8694330286558488E-03; -- double
  CONSTANT coeff66                        : real := -5.7401441060963761E-05; -- double
  CONSTANT coeff67                        : real := 3.7505572796232953E-03; -- double
  CONSTANT coeff68                        : real := 6.7957109278883451E-03; -- double
  CONSTANT coeff69                        : real := 8.4236235733441602E-03; -- double
  CONSTANT coeff70                        : real := 8.2184753831075139E-03; -- double
  CONSTANT coeff71                        : real := 6.0992433529429031E-03; -- double
  CONSTANT coeff72                        : real := 2.3571023269763928E-03; -- double
  CONSTANT coeff73                        : real := -2.3766058933807886E-03; -- double
  CONSTANT coeff74                        : real := -7.2299749185647027E-03; -- double
  CONSTANT coeff75                        : real := -1.1243014684758848E-02; -- double
  CONSTANT coeff76                        : real := -1.3547528278711380E-02; -- double
  CONSTANT coeff77                        : real := -1.3542248403202799E-02; -- double
  CONSTANT coeff78                        : real := -1.1030009028798212E-02; -- double
  CONSTANT coeff79                        : real := -6.2886825233574670E-03; -- double
  CONSTANT coeff80                        : real := -5.8010247123908097E-05; -- double
  CONSTANT coeff81                        : real := 6.5613170199883691E-03; -- double
  CONSTANT coeff82                        : real := 1.2284287566187961E-02; -- double
  CONSTANT coeff83                        : real := 1.5867463148745566E-02; -- double
  CONSTANT coeff84                        : real := 1.6347206946257433E-02; -- double
  CONSTANT coeff85                        : real := 1.3248782120487364E-02; -- double
  CONSTANT coeff86                        : real := 6.7273652042791499E-03; -- double
  CONSTANT coeff87                        : real := -2.3885506357348135E-03; -- double
  CONSTANT coeff88                        : real := -1.2665861995416212E-02; -- double
  CONSTANT coeff89                        : real := -2.2243903796322344E-02; -- double
  CONSTANT coeff90                        : real := -2.9097564473858192E-02; -- double
  CONSTANT coeff91                        : real := -3.1348591318253023E-02; -- double
  CONSTANT coeff92                        : real := -2.7577272144798319E-02; -- double
  CONSTANT coeff93                        : real := -1.7084285299362453E-02; -- double
  CONSTANT coeff94                        : real := -5.8316337104179425E-05; -- double
  CONSTANT coeff95                        : real := 2.2381661221191458E-02; -- double
  CONSTANT coeff96                        : real := 4.8281736254252229E-02; -- double
  CONSTANT coeff97                        : real := 7.5076973456069854E-02; -- double
  CONSTANT coeff98                        : real := 9.9914343896981464E-02; -- double
  CONSTANT coeff99                        : real := 1.2002889453982224E-01; -- double
  CONSTANT coeff100                       : real := 1.3311810628060192E-01; -- double
  CONSTANT coeff101                       : real := 1.3765868454010427E-01; -- double
  CONSTANT coeff102                       : real := 1.3311810628060192E-01; -- double
  CONSTANT coeff103                       : real := 1.2002889453982224E-01; -- double
  CONSTANT coeff104                       : real := 9.9914343896981464E-02; -- double
  CONSTANT coeff105                       : real := 7.5076973456069854E-02; -- double
  CONSTANT coeff106                       : real := 4.8281736254252229E-02; -- double
  CONSTANT coeff107                       : real := 2.2381661221191458E-02; -- double
  CONSTANT coeff108                       : real := -5.8316337104179425E-05; -- double
  CONSTANT coeff109                       : real := -1.7084285299362453E-02; -- double
  CONSTANT coeff110                       : real := -2.7577272144798319E-02; -- double
  CONSTANT coeff111                       : real := -3.1348591318253023E-02; -- double
  CONSTANT coeff112                       : real := -2.9097564473858192E-02; -- double
  CONSTANT coeff113                       : real := -2.2243903796322344E-02; -- double
  CONSTANT coeff114                       : real := -1.2665861995416212E-02; -- double
  CONSTANT coeff115                       : real := -2.3885506357348135E-03; -- double
  CONSTANT coeff116                       : real := 6.7273652042791499E-03; -- double
  CONSTANT coeff117                       : real := 1.3248782120487364E-02; -- double
  CONSTANT coeff118                       : real := 1.6347206946257433E-02; -- double
  CONSTANT coeff119                       : real := 1.5867463148745566E-02; -- double
  CONSTANT coeff120                       : real := 1.2284287566187961E-02; -- double
  CONSTANT coeff121                       : real := 6.5613170199883691E-03; -- double
  CONSTANT coeff122                       : real := -5.8010247123908097E-05; -- double
  CONSTANT coeff123                       : real := -6.2886825233574670E-03; -- double
  CONSTANT coeff124                       : real := -1.1030009028798212E-02; -- double
  CONSTANT coeff125                       : real := -1.3542248403202799E-02; -- double
  CONSTANT coeff126                       : real := -1.3547528278711380E-02; -- double
  CONSTANT coeff127                       : real := -1.1243014684758848E-02; -- double
  CONSTANT coeff128                       : real := -7.2299749185647027E-03; -- double
  CONSTANT coeff129                       : real := -2.3766058933807886E-03; -- double
  CONSTANT coeff130                       : real := 2.3571023269763928E-03; -- double
  CONSTANT coeff131                       : real := 6.0992433529429031E-03; -- double
  CONSTANT coeff132                       : real := 8.2184753831075139E-03; -- double
  CONSTANT coeff133                       : real := 8.4236235733441602E-03; -- double
  CONSTANT coeff134                       : real := 6.7957109278883451E-03; -- double
  CONSTANT coeff135                       : real := 3.7505572796232953E-03; -- double
  CONSTANT coeff136                       : real := -5.7401441060963761E-05; -- double
  CONSTANT coeff137                       : real := -3.8694330286558488E-03; -- double
  CONSTANT coeff138                       : real := -6.9685249545193059E-03; -- double
  CONSTANT coeff139                       : real := -8.8098827781718392E-03; -- double
  CONSTANT coeff140                       : real := -9.1128689950590331E-03; -- double
  CONSTANT coeff141                       : real := -7.8994828919364928E-03; -- double
  CONSTANT coeff142                       : real := -5.4749506577907543E-03; -- double
  CONSTANT coeff143                       : real := -2.3567933886536911E-03; -- double
  CONSTANT coeff144                       : real := 8.3210563195582022E-04; -- double
  CONSTANT coeff145                       : real := 3.4850002052213701E-03; -- double
  CONSTANT coeff146                       : real := 5.1241843972648542E-03; -- double
  CONSTANT coeff147                       : real := 5.4847365180753982E-03; -- double
  CONSTANT coeff148                       : real := 4.5548160761323857E-03; -- double
  CONSTANT coeff149                       : real := 2.5668771868283171E-03; -- double
  CONSTANT coeff150                       : real := -5.6496624397325032E-05; -- double
  CONSTANT coeff151                       : real := -2.7901487836302845E-03; -- double
  CONSTANT coeff152                       : real := -5.1095753082449902E-03; -- double
  CONSTANT coeff153                       : real := -6.5898759378009543E-03; -- double
  CONSTANT coeff154                       : real := -6.9820582925067308E-03; -- double
  CONSTANT coeff155                       : real := -6.2532559947046972E-03; -- double
  CONSTANT coeff156                       : real := -4.5846783292933548E-03; -- double
  CONSTANT coeff157                       : real := -2.3292552928086186E-03; -- double
  CONSTANT coeff158                       : real := 6.1571629011121859E-05; -- double
  CONSTANT coeff159                       : real := 2.1270097333804367E-03; -- double
  CONSTANT coeff160                       : real := 3.4846526317990423E-03; -- double
  CONSTANT coeff161                       : real := 3.9002938803194623E-03; -- double
  CONSTANT coeff162                       : real := 3.3272561150024058E-03; -- double
  CONSTANT coeff163                       : real := 1.9088437575590857E-03; -- double
  CONSTANT coeff164                       : real := -5.5305750134082332E-05; -- double
  CONSTANT coeff165                       : real := -2.1714099556521507E-03; -- double
  CONSTANT coeff166                       : real := -4.0295622826544853E-03; -- double
  CONSTANT coeff167                       : real := -5.2822943985271313E-03; -- double
  CONSTANT coeff168                       : real := -5.7087699577777432E-03; -- double
  CONSTANT coeff169                       : real := -5.2528844063507614E-03; -- double
  CONSTANT coeff170                       : real := -4.0288483506097945E-03; -- double
  CONSTANT coeff171                       : real := -2.2941888005472916E-03; -- double
  CONSTANT coeff172                       : real := -3.9628186259847400E-04; -- double
  CONSTANT coeff173                       : real := 1.2966302022281505E-03; -- double
  CONSTANT coeff174                       : real := 2.4663614308932120E-03; -- double
  CONSTANT coeff175                       : real := 2.9040937623714389E-03; -- double
  CONSTANT coeff176                       : real := 2.5471222690863424E-03; -- double
  CONSTANT coeff177                       : real := 1.4866789005439521E-03; -- double
  CONSTANT coeff178                       : real := -5.3841894088120829E-05; -- double
  CONSTANT coeff179                       : real := -1.7652821280141869E-03; -- double
  CONSTANT coeff180                       : real := -3.3142196638273756E-03; -- double
  CONSTANT coeff181                       : real := -4.4074270615698128E-03; -- double
  CONSTANT coeff182                       : real := -4.8469114634968231E-03; -- double
  CONSTANT coeff183                       : real := -4.5652814102443177E-03; -- double
  CONSTANT coeff184                       : real := -3.6352071434542907E-03; -- double
  CONSTANT coeff185                       : real := -2.2518443082332504E-03; -- double
  CONSTANT coeff186                       : real := -6.9227834862994192E-04; -- double
  CONSTANT coeff187                       : real := 7.3967119962025448E-04; -- double
  CONSTANT coeff188                       : real := 1.7723634652808443E-03; -- double
  CONSTANT coeff189                       : real := 2.2176071268367680E-03; -- double
  CONSTANT coeff190                       : real := 2.0046726876392241E-03; -- double
  CONSTANT coeff191                       : real := 1.1909642541081957E-03; -- double
  CONSTANT coeff192                       : real := -5.2121091202658914E-05; -- double
  CONSTANT coeff193                       : real := -1.4748383764726239E-03; -- double
  CONSTANT coeff194                       : real := -2.7989027828169135E-03; -- double
  CONSTANT coeff195                       : real := -3.7715841910819022E-03; -- double
  CONSTANT coeff196                       : real := -4.2136243650270667E-03; -- double
  CONSTANT coeff197                       : real := -4.0519399355335595E-03; -- double
  CONSTANT coeff198                       : real := -3.3311967217403678E-03; -- double
  CONSTANT coeff199                       : real := -2.2025231045459236E-03; -- double
  CONSTANT coeff200                       : real := -8.9204858579275967E-04; -- double
  CONSTANT coeff201                       : real := 3.4424189839880881E-04; -- double

  -- Signals
  SIGNAL delay_pipeline                   : delay_pipeline_type(0 TO 200) := (0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0, 0.0); -- double
  SIGNAL product201                       : real := 0.0; -- double
  SIGNAL product200                       : real := 0.0; -- double
  SIGNAL product199                       : real := 0.0; -- double
  SIGNAL product198                       : real := 0.0; -- double
  SIGNAL product197                       : real := 0.0; -- double
  SIGNAL product196                       : real := 0.0; -- double
  SIGNAL product195                       : real := 0.0; -- double
  SIGNAL product194                       : real := 0.0; -- double
  SIGNAL product193                       : real := 0.0; -- double
  SIGNAL product192                       : real := 0.0; -- double
  SIGNAL product191                       : real := 0.0; -- double
  SIGNAL product190                       : real := 0.0; -- double
  SIGNAL product189                       : real := 0.0; -- double
  SIGNAL product188                       : real := 0.0; -- double
  SIGNAL product187                       : real := 0.0; -- double
  SIGNAL product186                       : real := 0.0; -- double
  SIGNAL product185                       : real := 0.0; -- double
  SIGNAL product184                       : real := 0.0; -- double
  SIGNAL product183                       : real := 0.0; -- double
  SIGNAL product182                       : real := 0.0; -- double
  SIGNAL product181                       : real := 0.0; -- double
  SIGNAL product180                       : real := 0.0; -- double
  SIGNAL product179                       : real := 0.0; -- double
  SIGNAL product178                       : real := 0.0; -- double
  SIGNAL product177                       : real := 0.0; -- double
  SIGNAL product176                       : real := 0.0; -- double
  SIGNAL product175                       : real := 0.0; -- double
  SIGNAL product174                       : real := 0.0; -- double
  SIGNAL product173                       : real := 0.0; -- double
  SIGNAL product172                       : real := 0.0; -- double
  SIGNAL product171                       : real := 0.0; -- double
  SIGNAL product170                       : real := 0.0; -- double
  SIGNAL product169                       : real := 0.0; -- double
  SIGNAL product168                       : real := 0.0; -- double
  SIGNAL product167                       : real := 0.0; -- double
  SIGNAL product166                       : real := 0.0; -- double
  SIGNAL product165                       : real := 0.0; -- double
  SIGNAL product164                       : real := 0.0; -- double
  SIGNAL product163                       : real := 0.0; -- double
  SIGNAL product162                       : real := 0.0; -- double
  SIGNAL product161                       : real := 0.0; -- double
  SIGNAL product160                       : real := 0.0; -- double
  SIGNAL product159                       : real := 0.0; -- double
  SIGNAL product158                       : real := 0.0; -- double
  SIGNAL product157                       : real := 0.0; -- double
  SIGNAL product156                       : real := 0.0; -- double
  SIGNAL product155                       : real := 0.0; -- double
  SIGNAL product154                       : real := 0.0; -- double
  SIGNAL product153                       : real := 0.0; -- double
  SIGNAL product152                       : real := 0.0; -- double
  SIGNAL product151                       : real := 0.0; -- double
  SIGNAL product150                       : real := 0.0; -- double
  SIGNAL product149                       : real := 0.0; -- double
  SIGNAL product148                       : real := 0.0; -- double
  SIGNAL product147                       : real := 0.0; -- double
  SIGNAL product146                       : real := 0.0; -- double
  SIGNAL product145                       : real := 0.0; -- double
  SIGNAL product144                       : real := 0.0; -- double
  SIGNAL product143                       : real := 0.0; -- double
  SIGNAL product142                       : real := 0.0; -- double
  SIGNAL product141                       : real := 0.0; -- double
  SIGNAL product140                       : real := 0.0; -- double
  SIGNAL product139                       : real := 0.0; -- double
  SIGNAL product138                       : real := 0.0; -- double
  SIGNAL product137                       : real := 0.0; -- double
  SIGNAL product136                       : real := 0.0; -- double
  SIGNAL product135                       : real := 0.0; -- double
  SIGNAL product134                       : real := 0.0; -- double
  SIGNAL product133                       : real := 0.0; -- double
  SIGNAL product132                       : real := 0.0; -- double
  SIGNAL product131                       : real := 0.0; -- double
  SIGNAL product130                       : real := 0.0; -- double
  SIGNAL product129                       : real := 0.0; -- double
  SIGNAL product128                       : real := 0.0; -- double
  SIGNAL product127                       : real := 0.0; -- double
  SIGNAL product126                       : real := 0.0; -- double
  SIGNAL product125                       : real := 0.0; -- double
  SIGNAL product124                       : real := 0.0; -- double
  SIGNAL product123                       : real := 0.0; -- double
  SIGNAL product122                       : real := 0.0; -- double
  SIGNAL product121                       : real := 0.0; -- double
  SIGNAL product120                       : real := 0.0; -- double
  SIGNAL product119                       : real := 0.0; -- double
  SIGNAL product118                       : real := 0.0; -- double
  SIGNAL product117                       : real := 0.0; -- double
  SIGNAL product116                       : real := 0.0; -- double
  SIGNAL product115                       : real := 0.0; -- double
  SIGNAL product114                       : real := 0.0; -- double
  SIGNAL product113                       : real := 0.0; -- double
  SIGNAL product112                       : real := 0.0; -- double
  SIGNAL product111                       : real := 0.0; -- double
  SIGNAL product110                       : real := 0.0; -- double
  SIGNAL product109                       : real := 0.0; -- double
  SIGNAL product108                       : real := 0.0; -- double
  SIGNAL product107                       : real := 0.0; -- double
  SIGNAL product106                       : real := 0.0; -- double
  SIGNAL product105                       : real := 0.0; -- double
  SIGNAL product104                       : real := 0.0; -- double
  SIGNAL product103                       : real := 0.0; -- double
  SIGNAL product102                       : real := 0.0; -- double
  SIGNAL product101                       : real := 0.0; -- double
  SIGNAL product100                       : real := 0.0; -- double
  SIGNAL product99                        : real := 0.0; -- double
  SIGNAL product98                        : real := 0.0; -- double
  SIGNAL product97                        : real := 0.0; -- double
  SIGNAL product96                        : real := 0.0; -- double
  SIGNAL product95                        : real := 0.0; -- double
  SIGNAL product94                        : real := 0.0; -- double
  SIGNAL product93                        : real := 0.0; -- double
  SIGNAL product92                        : real := 0.0; -- double
  SIGNAL product91                        : real := 0.0; -- double
  SIGNAL product90                        : real := 0.0; -- double
  SIGNAL product89                        : real := 0.0; -- double
  SIGNAL product88                        : real := 0.0; -- double
  SIGNAL product87                        : real := 0.0; -- double
  SIGNAL product86                        : real := 0.0; -- double
  SIGNAL product85                        : real := 0.0; -- double
  SIGNAL product84                        : real := 0.0; -- double
  SIGNAL product83                        : real := 0.0; -- double
  SIGNAL product82                        : real := 0.0; -- double
  SIGNAL product81                        : real := 0.0; -- double
  SIGNAL product80                        : real := 0.0; -- double
  SIGNAL product79                        : real := 0.0; -- double
  SIGNAL product78                        : real := 0.0; -- double
  SIGNAL product77                        : real := 0.0; -- double
  SIGNAL product76                        : real := 0.0; -- double
  SIGNAL product75                        : real := 0.0; -- double
  SIGNAL product74                        : real := 0.0; -- double
  SIGNAL product73                        : real := 0.0; -- double
  SIGNAL product72                        : real := 0.0; -- double
  SIGNAL product71                        : real := 0.0; -- double
  SIGNAL product70                        : real := 0.0; -- double
  SIGNAL product69                        : real := 0.0; -- double
  SIGNAL product68                        : real := 0.0; -- double
  SIGNAL product67                        : real := 0.0; -- double
  SIGNAL product66                        : real := 0.0; -- double
  SIGNAL product65                        : real := 0.0; -- double
  SIGNAL product64                        : real := 0.0; -- double
  SIGNAL product63                        : real := 0.0; -- double
  SIGNAL product62                        : real := 0.0; -- double
  SIGNAL product61                        : real := 0.0; -- double
  SIGNAL product60                        : real := 0.0; -- double
  SIGNAL product59                        : real := 0.0; -- double
  SIGNAL product58                        : real := 0.0; -- double
  SIGNAL product57                        : real := 0.0; -- double
  SIGNAL product56                        : real := 0.0; -- double
  SIGNAL product55                        : real := 0.0; -- double
  SIGNAL product54                        : real := 0.0; -- double
  SIGNAL product53                        : real := 0.0; -- double
  SIGNAL product52                        : real := 0.0; -- double
  SIGNAL product51                        : real := 0.0; -- double
  SIGNAL product50                        : real := 0.0; -- double
  SIGNAL product49                        : real := 0.0; -- double
  SIGNAL product48                        : real := 0.0; -- double
  SIGNAL product47                        : real := 0.0; -- double
  SIGNAL product46                        : real := 0.0; -- double
  SIGNAL product45                        : real := 0.0; -- double
  SIGNAL product44                        : real := 0.0; -- double
  SIGNAL product43                        : real := 0.0; -- double
  SIGNAL product42                        : real := 0.0; -- double
  SIGNAL product41                        : real := 0.0; -- double
  SIGNAL product40                        : real := 0.0; -- double
  SIGNAL product39                        : real := 0.0; -- double
  SIGNAL product38                        : real := 0.0; -- double
  SIGNAL product37                        : real := 0.0; -- double
  SIGNAL product36                        : real := 0.0; -- double
  SIGNAL product35                        : real := 0.0; -- double
  SIGNAL product34                        : real := 0.0; -- double
  SIGNAL product33                        : real := 0.0; -- double
  SIGNAL product32                        : real := 0.0; -- double
  SIGNAL product31                        : real := 0.0; -- double
  SIGNAL product30                        : real := 0.0; -- double
  SIGNAL product29                        : real := 0.0; -- double
  SIGNAL product28                        : real := 0.0; -- double
  SIGNAL product27                        : real := 0.0; -- double
  SIGNAL product26                        : real := 0.0; -- double
  SIGNAL product25                        : real := 0.0; -- double
  SIGNAL product24                        : real := 0.0; -- double
  SIGNAL product23                        : real := 0.0; -- double
  SIGNAL product22                        : real := 0.0; -- double
  SIGNAL product21                        : real := 0.0; -- double
  SIGNAL product20                        : real := 0.0; -- double
  SIGNAL product19                        : real := 0.0; -- double
  SIGNAL product18                        : real := 0.0; -- double
  SIGNAL product17                        : real := 0.0; -- double
  SIGNAL product16                        : real := 0.0; -- double
  SIGNAL product15                        : real := 0.0; -- double
  SIGNAL product14                        : real := 0.0; -- double
  SIGNAL product13                        : real := 0.0; -- double
  SIGNAL product12                        : real := 0.0; -- double
  SIGNAL product11                        : real := 0.0; -- double
  SIGNAL product10                        : real := 0.0; -- double
  SIGNAL product9                         : real := 0.0; -- double
  SIGNAL product8                         : real := 0.0; -- double
  SIGNAL product7                         : real := 0.0; -- double
  SIGNAL product6                         : real := 0.0; -- double
  SIGNAL product5                         : real := 0.0; -- double
  SIGNAL product4                         : real := 0.0; -- double
  SIGNAL product3                         : real := 0.0; -- double
  SIGNAL product2                         : real := 0.0; -- double
  SIGNAL product1_cast                    : real := 0.0; -- double
  SIGNAL product1                         : real := 0.0; -- double
  SIGNAL sum1                             : real := 0.0; -- double
  SIGNAL sum2                             : real := 0.0; -- double
  SIGNAL sum3                             : real := 0.0; -- double
  SIGNAL sum4                             : real := 0.0; -- double
  SIGNAL sum5                             : real := 0.0; -- double
  SIGNAL sum6                             : real := 0.0; -- double
  SIGNAL sum7                             : real := 0.0; -- double
  SIGNAL sum8                             : real := 0.0; -- double
  SIGNAL sum9                             : real := 0.0; -- double
  SIGNAL sum10                            : real := 0.0; -- double
  SIGNAL sum11                            : real := 0.0; -- double
  SIGNAL sum12                            : real := 0.0; -- double
  SIGNAL sum13                            : real := 0.0; -- double
  SIGNAL sum14                            : real := 0.0; -- double
  SIGNAL sum15                            : real := 0.0; -- double
  SIGNAL sum16                            : real := 0.0; -- double
  SIGNAL sum17                            : real := 0.0; -- double
  SIGNAL sum18                            : real := 0.0; -- double
  SIGNAL sum19                            : real := 0.0; -- double
  SIGNAL sum20                            : real := 0.0; -- double
  SIGNAL sum21                            : real := 0.0; -- double
  SIGNAL sum22                            : real := 0.0; -- double
  SIGNAL sum23                            : real := 0.0; -- double
  SIGNAL sum24                            : real := 0.0; -- double
  SIGNAL sum25                            : real := 0.0; -- double
  SIGNAL sum26                            : real := 0.0; -- double
  SIGNAL sum27                            : real := 0.0; -- double
  SIGNAL sum28                            : real := 0.0; -- double
  SIGNAL sum29                            : real := 0.0; -- double
  SIGNAL sum30                            : real := 0.0; -- double
  SIGNAL sum31                            : real := 0.0; -- double
  SIGNAL sum32                            : real := 0.0; -- double
  SIGNAL sum33                            : real := 0.0; -- double
  SIGNAL sum34                            : real := 0.0; -- double
  SIGNAL sum35                            : real := 0.0; -- double
  SIGNAL sum36                            : real := 0.0; -- double
  SIGNAL sum37                            : real := 0.0; -- double
  SIGNAL sum38                            : real := 0.0; -- double
  SIGNAL sum39                            : real := 0.0; -- double
  SIGNAL sum40                            : real := 0.0; -- double
  SIGNAL sum41                            : real := 0.0; -- double
  SIGNAL sum42                            : real := 0.0; -- double
  SIGNAL sum43                            : real := 0.0; -- double
  SIGNAL sum44                            : real := 0.0; -- double
  SIGNAL sum45                            : real := 0.0; -- double
  SIGNAL sum46                            : real := 0.0; -- double
  SIGNAL sum47                            : real := 0.0; -- double
  SIGNAL sum48                            : real := 0.0; -- double
  SIGNAL sum49                            : real := 0.0; -- double
  SIGNAL sum50                            : real := 0.0; -- double
  SIGNAL sum51                            : real := 0.0; -- double
  SIGNAL sum52                            : real := 0.0; -- double
  SIGNAL sum53                            : real := 0.0; -- double
  SIGNAL sum54                            : real := 0.0; -- double
  SIGNAL sum55                            : real := 0.0; -- double
  SIGNAL sum56                            : real := 0.0; -- double
  SIGNAL sum57                            : real := 0.0; -- double
  SIGNAL sum58                            : real := 0.0; -- double
  SIGNAL sum59                            : real := 0.0; -- double
  SIGNAL sum60                            : real := 0.0; -- double
  SIGNAL sum61                            : real := 0.0; -- double
  SIGNAL sum62                            : real := 0.0; -- double
  SIGNAL sum63                            : real := 0.0; -- double
  SIGNAL sum64                            : real := 0.0; -- double
  SIGNAL sum65                            : real := 0.0; -- double
  SIGNAL sum66                            : real := 0.0; -- double
  SIGNAL sum67                            : real := 0.0; -- double
  SIGNAL sum68                            : real := 0.0; -- double
  SIGNAL sum69                            : real := 0.0; -- double
  SIGNAL sum70                            : real := 0.0; -- double
  SIGNAL sum71                            : real := 0.0; -- double
  SIGNAL sum72                            : real := 0.0; -- double
  SIGNAL sum73                            : real := 0.0; -- double
  SIGNAL sum74                            : real := 0.0; -- double
  SIGNAL sum75                            : real := 0.0; -- double
  SIGNAL sum76                            : real := 0.0; -- double
  SIGNAL sum77                            : real := 0.0; -- double
  SIGNAL sum78                            : real := 0.0; -- double
  SIGNAL sum79                            : real := 0.0; -- double
  SIGNAL sum80                            : real := 0.0; -- double
  SIGNAL sum81                            : real := 0.0; -- double
  SIGNAL sum82                            : real := 0.0; -- double
  SIGNAL sum83                            : real := 0.0; -- double
  SIGNAL sum84                            : real := 0.0; -- double
  SIGNAL sum85                            : real := 0.0; -- double
  SIGNAL sum86                            : real := 0.0; -- double
  SIGNAL sum87                            : real := 0.0; -- double
  SIGNAL sum88                            : real := 0.0; -- double
  SIGNAL sum89                            : real := 0.0; -- double
  SIGNAL sum90                            : real := 0.0; -- double
  SIGNAL sum91                            : real := 0.0; -- double
  SIGNAL sum92                            : real := 0.0; -- double
  SIGNAL sum93                            : real := 0.0; -- double
  SIGNAL sum94                            : real := 0.0; -- double
  SIGNAL sum95                            : real := 0.0; -- double
  SIGNAL sum96                            : real := 0.0; -- double
  SIGNAL sum97                            : real := 0.0; -- double
  SIGNAL sum98                            : real := 0.0; -- double
  SIGNAL sum99                            : real := 0.0; -- double
  SIGNAL sum100                           : real := 0.0; -- double
  SIGNAL sum101                           : real := 0.0; -- double
  SIGNAL sum102                           : real := 0.0; -- double
  SIGNAL sum103                           : real := 0.0; -- double
  SIGNAL sum104                           : real := 0.0; -- double
  SIGNAL sum105                           : real := 0.0; -- double
  SIGNAL sum106                           : real := 0.0; -- double
  SIGNAL sum107                           : real := 0.0; -- double
  SIGNAL sum108                           : real := 0.0; -- double
  SIGNAL sum109                           : real := 0.0; -- double
  SIGNAL sum110                           : real := 0.0; -- double
  SIGNAL sum111                           : real := 0.0; -- double
  SIGNAL sum112                           : real := 0.0; -- double
  SIGNAL sum113                           : real := 0.0; -- double
  SIGNAL sum114                           : real := 0.0; -- double
  SIGNAL sum115                           : real := 0.0; -- double
  SIGNAL sum116                           : real := 0.0; -- double
  SIGNAL sum117                           : real := 0.0; -- double
  SIGNAL sum118                           : real := 0.0; -- double
  SIGNAL sum119                           : real := 0.0; -- double
  SIGNAL sum120                           : real := 0.0; -- double
  SIGNAL sum121                           : real := 0.0; -- double
  SIGNAL sum122                           : real := 0.0; -- double
  SIGNAL sum123                           : real := 0.0; -- double
  SIGNAL sum124                           : real := 0.0; -- double
  SIGNAL sum125                           : real := 0.0; -- double
  SIGNAL sum126                           : real := 0.0; -- double
  SIGNAL sum127                           : real := 0.0; -- double
  SIGNAL sum128                           : real := 0.0; -- double
  SIGNAL sum129                           : real := 0.0; -- double
  SIGNAL sum130                           : real := 0.0; -- double
  SIGNAL sum131                           : real := 0.0; -- double
  SIGNAL sum132                           : real := 0.0; -- double
  SIGNAL sum133                           : real := 0.0; -- double
  SIGNAL sum134                           : real := 0.0; -- double
  SIGNAL sum135                           : real := 0.0; -- double
  SIGNAL sum136                           : real := 0.0; -- double
  SIGNAL sum137                           : real := 0.0; -- double
  SIGNAL sum138                           : real := 0.0; -- double
  SIGNAL sum139                           : real := 0.0; -- double
  SIGNAL sum140                           : real := 0.0; -- double
  SIGNAL sum141                           : real := 0.0; -- double
  SIGNAL sum142                           : real := 0.0; -- double
  SIGNAL sum143                           : real := 0.0; -- double
  SIGNAL sum144                           : real := 0.0; -- double
  SIGNAL sum145                           : real := 0.0; -- double
  SIGNAL sum146                           : real := 0.0; -- double
  SIGNAL sum147                           : real := 0.0; -- double
  SIGNAL sum148                           : real := 0.0; -- double
  SIGNAL sum149                           : real := 0.0; -- double
  SIGNAL sum150                           : real := 0.0; -- double
  SIGNAL sum151                           : real := 0.0; -- double
  SIGNAL sum152                           : real := 0.0; -- double
  SIGNAL sum153                           : real := 0.0; -- double
  SIGNAL sum154                           : real := 0.0; -- double
  SIGNAL sum155                           : real := 0.0; -- double
  SIGNAL sum156                           : real := 0.0; -- double
  SIGNAL sum157                           : real := 0.0; -- double
  SIGNAL sum158                           : real := 0.0; -- double
  SIGNAL sum159                           : real := 0.0; -- double
  SIGNAL sum160                           : real := 0.0; -- double
  SIGNAL sum161                           : real := 0.0; -- double
  SIGNAL sum162                           : real := 0.0; -- double
  SIGNAL sum163                           : real := 0.0; -- double
  SIGNAL sum164                           : real := 0.0; -- double
  SIGNAL sum165                           : real := 0.0; -- double
  SIGNAL sum166                           : real := 0.0; -- double
  SIGNAL sum167                           : real := 0.0; -- double
  SIGNAL sum168                           : real := 0.0; -- double
  SIGNAL sum169                           : real := 0.0; -- double
  SIGNAL sum170                           : real := 0.0; -- double
  SIGNAL sum171                           : real := 0.0; -- double
  SIGNAL sum172                           : real := 0.0; -- double
  SIGNAL sum173                           : real := 0.0; -- double
  SIGNAL sum174                           : real := 0.0; -- double
  SIGNAL sum175                           : real := 0.0; -- double
  SIGNAL sum176                           : real := 0.0; -- double
  SIGNAL sum177                           : real := 0.0; -- double
  SIGNAL sum178                           : real := 0.0; -- double
  SIGNAL sum179                           : real := 0.0; -- double
  SIGNAL sum180                           : real := 0.0; -- double
  SIGNAL sum181                           : real := 0.0; -- double
  SIGNAL sum182                           : real := 0.0; -- double
  SIGNAL sum183                           : real := 0.0; -- double
  SIGNAL sum184                           : real := 0.0; -- double
  SIGNAL sum185                           : real := 0.0; -- double
  SIGNAL sum186                           : real := 0.0; -- double
  SIGNAL sum187                           : real := 0.0; -- double
  SIGNAL sum188                           : real := 0.0; -- double
  SIGNAL sum189                           : real := 0.0; -- double
  SIGNAL sum190                           : real := 0.0; -- double
  SIGNAL sum191                           : real := 0.0; -- double
  SIGNAL sum192                           : real := 0.0; -- double
  SIGNAL sum193                           : real := 0.0; -- double
  SIGNAL sum194                           : real := 0.0; -- double
  SIGNAL sum195                           : real := 0.0; -- double
  SIGNAL sum196                           : real := 0.0; -- double
  SIGNAL sum197                           : real := 0.0; -- double
  SIGNAL sum198                           : real := 0.0; -- double
  SIGNAL sum199                           : real := 0.0; -- double
  SIGNAL sum200                           : real := 0.0; -- double
  SIGNAL output_register                  : real := 0.0; -- double


BEGIN

  -- Block Statements
  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline(0 TO 200) <= (OTHERS => 0.0000000000000000E+00);
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        delay_pipeline(0) <= filter_in;
        delay_pipeline(1 TO 200) <= delay_pipeline(0 TO 199);
      END IF;
    END IF; 
  END PROCESS Delay_Pipeline_process;

  product201 <= delay_pipeline(200) * coeff201;

  product200 <= delay_pipeline(199) * coeff200;

  product199 <= delay_pipeline(198) * coeff199;

  product198 <= delay_pipeline(197) * coeff198;

  product197 <= delay_pipeline(196) * coeff197;

  product196 <= delay_pipeline(195) * coeff196;

  product195 <= delay_pipeline(194) * coeff195;

  product194 <= delay_pipeline(193) * coeff194;

  product193 <= delay_pipeline(192) * coeff193;

  product192 <= delay_pipeline(191) * coeff192;

  product191 <= delay_pipeline(190) * coeff191;

  product190 <= delay_pipeline(189) * coeff190;

  product189 <= delay_pipeline(188) * coeff189;

  product188 <= delay_pipeline(187) * coeff188;

  product187 <= delay_pipeline(186) * coeff187;

  product186 <= delay_pipeline(185) * coeff186;

  product185 <= delay_pipeline(184) * coeff185;

  product184 <= delay_pipeline(183) * coeff184;

  product183 <= delay_pipeline(182) * coeff183;

  product182 <= delay_pipeline(181) * coeff182;

  product181 <= delay_pipeline(180) * coeff181;

  product180 <= delay_pipeline(179) * coeff180;

  product179 <= delay_pipeline(178) * coeff179;

  product178 <= delay_pipeline(177) * coeff178;

  product177 <= delay_pipeline(176) * coeff177;

  product176 <= delay_pipeline(175) * coeff176;

  product175 <= delay_pipeline(174) * coeff175;

  product174 <= delay_pipeline(173) * coeff174;

  product173 <= delay_pipeline(172) * coeff173;

  product172 <= delay_pipeline(171) * coeff172;

  product171 <= delay_pipeline(170) * coeff171;

  product170 <= delay_pipeline(169) * coeff170;

  product169 <= delay_pipeline(168) * coeff169;

  product168 <= delay_pipeline(167) * coeff168;

  product167 <= delay_pipeline(166) * coeff167;

  product166 <= delay_pipeline(165) * coeff166;

  product165 <= delay_pipeline(164) * coeff165;

  product164 <= delay_pipeline(163) * coeff164;

  product163 <= delay_pipeline(162) * coeff163;

  product162 <= delay_pipeline(161) * coeff162;

  product161 <= delay_pipeline(160) * coeff161;

  product160 <= delay_pipeline(159) * coeff160;

  product159 <= delay_pipeline(158) * coeff159;

  product158 <= delay_pipeline(157) * coeff158;

  product157 <= delay_pipeline(156) * coeff157;

  product156 <= delay_pipeline(155) * coeff156;

  product155 <= delay_pipeline(154) * coeff155;

  product154 <= delay_pipeline(153) * coeff154;

  product153 <= delay_pipeline(152) * coeff153;

  product152 <= delay_pipeline(151) * coeff152;

  product151 <= delay_pipeline(150) * coeff151;

  product150 <= delay_pipeline(149) * coeff150;

  product149 <= delay_pipeline(148) * coeff149;

  product148 <= delay_pipeline(147) * coeff148;

  product147 <= delay_pipeline(146) * coeff147;

  product146 <= delay_pipeline(145) * coeff146;

  product145 <= delay_pipeline(144) * coeff145;

  product144 <= delay_pipeline(143) * coeff144;

  product143 <= delay_pipeline(142) * coeff143;

  product142 <= delay_pipeline(141) * coeff142;

  product141 <= delay_pipeline(140) * coeff141;

  product140 <= delay_pipeline(139) * coeff140;

  product139 <= delay_pipeline(138) * coeff139;

  product138 <= delay_pipeline(137) * coeff138;

  product137 <= delay_pipeline(136) * coeff137;

  product136 <= delay_pipeline(135) * coeff136;

  product135 <= delay_pipeline(134) * coeff135;

  product134 <= delay_pipeline(133) * coeff134;

  product133 <= delay_pipeline(132) * coeff133;

  product132 <= delay_pipeline(131) * coeff132;

  product131 <= delay_pipeline(130) * coeff131;

  product130 <= delay_pipeline(129) * coeff130;

  product129 <= delay_pipeline(128) * coeff129;

  product128 <= delay_pipeline(127) * coeff128;

  product127 <= delay_pipeline(126) * coeff127;

  product126 <= delay_pipeline(125) * coeff126;

  product125 <= delay_pipeline(124) * coeff125;

  product124 <= delay_pipeline(123) * coeff124;

  product123 <= delay_pipeline(122) * coeff123;

  product122 <= delay_pipeline(121) * coeff122;

  product121 <= delay_pipeline(120) * coeff121;

  product120 <= delay_pipeline(119) * coeff120;

  product119 <= delay_pipeline(118) * coeff119;

  product118 <= delay_pipeline(117) * coeff118;

  product117 <= delay_pipeline(116) * coeff117;

  product116 <= delay_pipeline(115) * coeff116;

  product115 <= delay_pipeline(114) * coeff115;

  product114 <= delay_pipeline(113) * coeff114;

  product113 <= delay_pipeline(112) * coeff113;

  product112 <= delay_pipeline(111) * coeff112;

  product111 <= delay_pipeline(110) * coeff111;

  product110 <= delay_pipeline(109) * coeff110;

  product109 <= delay_pipeline(108) * coeff109;

  product108 <= delay_pipeline(107) * coeff108;

  product107 <= delay_pipeline(106) * coeff107;

  product106 <= delay_pipeline(105) * coeff106;

  product105 <= delay_pipeline(104) * coeff105;

  product104 <= delay_pipeline(103) * coeff104;

  product103 <= delay_pipeline(102) * coeff103;

  product102 <= delay_pipeline(101) * coeff102;

  product101 <= delay_pipeline(100) * coeff101;

  product100 <= delay_pipeline(99) * coeff100;

  product99 <= delay_pipeline(98) * coeff99;

  product98 <= delay_pipeline(97) * coeff98;

  product97 <= delay_pipeline(96) * coeff97;

  product96 <= delay_pipeline(95) * coeff96;

  product95 <= delay_pipeline(94) * coeff95;

  product94 <= delay_pipeline(93) * coeff94;

  product93 <= delay_pipeline(92) * coeff93;

  product92 <= delay_pipeline(91) * coeff92;

  product91 <= delay_pipeline(90) * coeff91;

  product90 <= delay_pipeline(89) * coeff90;

  product89 <= delay_pipeline(88) * coeff89;

  product88 <= delay_pipeline(87) * coeff88;

  product87 <= delay_pipeline(86) * coeff87;

  product86 <= delay_pipeline(85) * coeff86;

  product85 <= delay_pipeline(84) * coeff85;

  product84 <= delay_pipeline(83) * coeff84;

  product83 <= delay_pipeline(82) * coeff83;

  product82 <= delay_pipeline(81) * coeff82;

  product81 <= delay_pipeline(80) * coeff81;

  product80 <= delay_pipeline(79) * coeff80;

  product79 <= delay_pipeline(78) * coeff79;

  product78 <= delay_pipeline(77) * coeff78;

  product77 <= delay_pipeline(76) * coeff77;

  product76 <= delay_pipeline(75) * coeff76;

  product75 <= delay_pipeline(74) * coeff75;

  product74 <= delay_pipeline(73) * coeff74;

  product73 <= delay_pipeline(72) * coeff73;

  product72 <= delay_pipeline(71) * coeff72;

  product71 <= delay_pipeline(70) * coeff71;

  product70 <= delay_pipeline(69) * coeff70;

  product69 <= delay_pipeline(68) * coeff69;

  product68 <= delay_pipeline(67) * coeff68;

  product67 <= delay_pipeline(66) * coeff67;

  product66 <= delay_pipeline(65) * coeff66;

  product65 <= delay_pipeline(64) * coeff65;

  product64 <= delay_pipeline(63) * coeff64;

  product63 <= delay_pipeline(62) * coeff63;

  product62 <= delay_pipeline(61) * coeff62;

  product61 <= delay_pipeline(60) * coeff61;

  product60 <= delay_pipeline(59) * coeff60;

  product59 <= delay_pipeline(58) * coeff59;

  product58 <= delay_pipeline(57) * coeff58;

  product57 <= delay_pipeline(56) * coeff57;

  product56 <= delay_pipeline(55) * coeff56;

  product55 <= delay_pipeline(54) * coeff55;

  product54 <= delay_pipeline(53) * coeff54;

  product53 <= delay_pipeline(52) * coeff53;

  product52 <= delay_pipeline(51) * coeff52;

  product51 <= delay_pipeline(50) * coeff51;

  product50 <= delay_pipeline(49) * coeff50;

  product49 <= delay_pipeline(48) * coeff49;

  product48 <= delay_pipeline(47) * coeff48;

  product47 <= delay_pipeline(46) * coeff47;

  product46 <= delay_pipeline(45) * coeff46;

  product45 <= delay_pipeline(44) * coeff45;

  product44 <= delay_pipeline(43) * coeff44;

  product43 <= delay_pipeline(42) * coeff43;

  product42 <= delay_pipeline(41) * coeff42;

  product41 <= delay_pipeline(40) * coeff41;

  product40 <= delay_pipeline(39) * coeff40;

  product39 <= delay_pipeline(38) * coeff39;

  product38 <= delay_pipeline(37) * coeff38;

  product37 <= delay_pipeline(36) * coeff37;

  product36 <= delay_pipeline(35) * coeff36;

  product35 <= delay_pipeline(34) * coeff35;

  product34 <= delay_pipeline(33) * coeff34;

  product33 <= delay_pipeline(32) * coeff33;

  product32 <= delay_pipeline(31) * coeff32;

  product31 <= delay_pipeline(30) * coeff31;

  product30 <= delay_pipeline(29) * coeff30;

  product29 <= delay_pipeline(28) * coeff29;

  product28 <= delay_pipeline(27) * coeff28;

  product27 <= delay_pipeline(26) * coeff27;

  product26 <= delay_pipeline(25) * coeff26;

  product25 <= delay_pipeline(24) * coeff25;

  product24 <= delay_pipeline(23) * coeff24;

  product23 <= delay_pipeline(22) * coeff23;

  product22 <= delay_pipeline(21) * coeff22;

  product21 <= delay_pipeline(20) * coeff21;

  product20 <= delay_pipeline(19) * coeff20;

  product19 <= delay_pipeline(18) * coeff19;

  product18 <= delay_pipeline(17) * coeff18;

  product17 <= delay_pipeline(16) * coeff17;

  product16 <= delay_pipeline(15) * coeff16;

  product15 <= delay_pipeline(14) * coeff15;

  product14 <= delay_pipeline(13) * coeff14;

  product13 <= delay_pipeline(12) * coeff13;

  product12 <= delay_pipeline(11) * coeff12;

  product11 <= delay_pipeline(10) * coeff11;

  product10 <= delay_pipeline(9) * coeff10;

  product9 <= delay_pipeline(8) * coeff9;

  product8 <= delay_pipeline(7) * coeff8;

  product7 <= delay_pipeline(6) * coeff7;

  product6 <= delay_pipeline(5) * coeff6;

  product5 <= delay_pipeline(4) * coeff5;

  product4 <= delay_pipeline(3) * coeff4;

  product3 <= delay_pipeline(2) * coeff3;

  product2 <= delay_pipeline(1) * coeff2;

  product1_cast <= product1;


  product1 <= delay_pipeline(0) * coeff1;

  sum1 <= product1_cast + product2;

  sum2 <= sum1 + product3;

  sum3 <= sum2 + product4;

  sum4 <= sum3 + product5;

  sum5 <= sum4 + product6;

  sum6 <= sum5 + product7;

  sum7 <= sum6 + product8;

  sum8 <= sum7 + product9;

  sum9 <= sum8 + product10;

  sum10 <= sum9 + product11;

  sum11 <= sum10 + product12;

  sum12 <= sum11 + product13;

  sum13 <= sum12 + product14;

  sum14 <= sum13 + product15;

  sum15 <= sum14 + product16;

  sum16 <= sum15 + product17;

  sum17 <= sum16 + product18;

  sum18 <= sum17 + product19;

  sum19 <= sum18 + product20;

  sum20 <= sum19 + product21;

  sum21 <= sum20 + product22;

  sum22 <= sum21 + product23;

  sum23 <= sum22 + product24;

  sum24 <= sum23 + product25;

  sum25 <= sum24 + product26;

  sum26 <= sum25 + product27;

  sum27 <= sum26 + product28;

  sum28 <= sum27 + product29;

  sum29 <= sum28 + product30;

  sum30 <= sum29 + product31;

  sum31 <= sum30 + product32;

  sum32 <= sum31 + product33;

  sum33 <= sum32 + product34;

  sum34 <= sum33 + product35;

  sum35 <= sum34 + product36;

  sum36 <= sum35 + product37;

  sum37 <= sum36 + product38;

  sum38 <= sum37 + product39;

  sum39 <= sum38 + product40;

  sum40 <= sum39 + product41;

  sum41 <= sum40 + product42;

  sum42 <= sum41 + product43;

  sum43 <= sum42 + product44;

  sum44 <= sum43 + product45;

  sum45 <= sum44 + product46;

  sum46 <= sum45 + product47;

  sum47 <= sum46 + product48;

  sum48 <= sum47 + product49;

  sum49 <= sum48 + product50;

  sum50 <= sum49 + product51;

  sum51 <= sum50 + product52;

  sum52 <= sum51 + product53;

  sum53 <= sum52 + product54;

  sum54 <= sum53 + product55;

  sum55 <= sum54 + product56;

  sum56 <= sum55 + product57;

  sum57 <= sum56 + product58;

  sum58 <= sum57 + product59;

  sum59 <= sum58 + product60;

  sum60 <= sum59 + product61;

  sum61 <= sum60 + product62;

  sum62 <= sum61 + product63;

  sum63 <= sum62 + product64;

  sum64 <= sum63 + product65;

  sum65 <= sum64 + product66;

  sum66 <= sum65 + product67;

  sum67 <= sum66 + product68;

  sum68 <= sum67 + product69;

  sum69 <= sum68 + product70;

  sum70 <= sum69 + product71;

  sum71 <= sum70 + product72;

  sum72 <= sum71 + product73;

  sum73 <= sum72 + product74;

  sum74 <= sum73 + product75;

  sum75 <= sum74 + product76;

  sum76 <= sum75 + product77;

  sum77 <= sum76 + product78;

  sum78 <= sum77 + product79;

  sum79 <= sum78 + product80;

  sum80 <= sum79 + product81;

  sum81 <= sum80 + product82;

  sum82 <= sum81 + product83;

  sum83 <= sum82 + product84;

  sum84 <= sum83 + product85;

  sum85 <= sum84 + product86;

  sum86 <= sum85 + product87;

  sum87 <= sum86 + product88;

  sum88 <= sum87 + product89;

  sum89 <= sum88 + product90;

  sum90 <= sum89 + product91;

  sum91 <= sum90 + product92;

  sum92 <= sum91 + product93;

  sum93 <= sum92 + product94;

  sum94 <= sum93 + product95;

  sum95 <= sum94 + product96;

  sum96 <= sum95 + product97;

  sum97 <= sum96 + product98;

  sum98 <= sum97 + product99;

  sum99 <= sum98 + product100;

  sum100 <= sum99 + product101;

  sum101 <= sum100 + product102;

  sum102 <= sum101 + product103;

  sum103 <= sum102 + product104;

  sum104 <= sum103 + product105;

  sum105 <= sum104 + product106;

  sum106 <= sum105 + product107;

  sum107 <= sum106 + product108;

  sum108 <= sum107 + product109;

  sum109 <= sum108 + product110;

  sum110 <= sum109 + product111;

  sum111 <= sum110 + product112;

  sum112 <= sum111 + product113;

  sum113 <= sum112 + product114;

  sum114 <= sum113 + product115;

  sum115 <= sum114 + product116;

  sum116 <= sum115 + product117;

  sum117 <= sum116 + product118;

  sum118 <= sum117 + product119;

  sum119 <= sum118 + product120;

  sum120 <= sum119 + product121;

  sum121 <= sum120 + product122;

  sum122 <= sum121 + product123;

  sum123 <= sum122 + product124;

  sum124 <= sum123 + product125;

  sum125 <= sum124 + product126;

  sum126 <= sum125 + product127;

  sum127 <= sum126 + product128;

  sum128 <= sum127 + product129;

  sum129 <= sum128 + product130;

  sum130 <= sum129 + product131;

  sum131 <= sum130 + product132;

  sum132 <= sum131 + product133;

  sum133 <= sum132 + product134;

  sum134 <= sum133 + product135;

  sum135 <= sum134 + product136;

  sum136 <= sum135 + product137;

  sum137 <= sum136 + product138;

  sum138 <= sum137 + product139;

  sum139 <= sum138 + product140;

  sum140 <= sum139 + product141;

  sum141 <= sum140 + product142;

  sum142 <= sum141 + product143;

  sum143 <= sum142 + product144;

  sum144 <= sum143 + product145;

  sum145 <= sum144 + product146;

  sum146 <= sum145 + product147;

  sum147 <= sum146 + product148;

  sum148 <= sum147 + product149;

  sum149 <= sum148 + product150;

  sum150 <= sum149 + product151;

  sum151 <= sum150 + product152;

  sum152 <= sum151 + product153;

  sum153 <= sum152 + product154;

  sum154 <= sum153 + product155;

  sum155 <= sum154 + product156;

  sum156 <= sum155 + product157;

  sum157 <= sum156 + product158;

  sum158 <= sum157 + product159;

  sum159 <= sum158 + product160;

  sum160 <= sum159 + product161;

  sum161 <= sum160 + product162;

  sum162 <= sum161 + product163;

  sum163 <= sum162 + product164;

  sum164 <= sum163 + product165;

  sum165 <= sum164 + product166;

  sum166 <= sum165 + product167;

  sum167 <= sum166 + product168;

  sum168 <= sum167 + product169;

  sum169 <= sum168 + product170;

  sum170 <= sum169 + product171;

  sum171 <= sum170 + product172;

  sum172 <= sum171 + product173;

  sum173 <= sum172 + product174;

  sum174 <= sum173 + product175;

  sum175 <= sum174 + product176;

  sum176 <= sum175 + product177;

  sum177 <= sum176 + product178;

  sum178 <= sum177 + product179;

  sum179 <= sum178 + product180;

  sum180 <= sum179 + product181;

  sum181 <= sum180 + product182;

  sum182 <= sum181 + product183;

  sum183 <= sum182 + product184;

  sum184 <= sum183 + product185;

  sum185 <= sum184 + product186;

  sum186 <= sum185 + product187;

  sum187 <= sum186 + product188;

  sum188 <= sum187 + product189;

  sum189 <= sum188 + product190;

  sum190 <= sum189 + product191;

  sum191 <= sum190 + product192;

  sum192 <= sum191 + product193;

  sum193 <= sum192 + product194;

  sum194 <= sum193 + product195;

  sum195 <= sum194 + product196;

  sum196 <= sum195 + product197;

  sum197 <= sum196 + product198;

  sum198 <= sum197 + product199;

  sum199 <= sum198 + product200;

  sum200 <= sum199 + product201;

  Output_Register_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      output_register <= 0.0000000000000000E+00;
    ELSIF clk'event AND clk = '1' THEN
      IF clk_enable = '1' THEN
        output_register <= sum200;
      END IF;
    END IF; 
  END PROCESS Output_Register_process;

  -- Assignment Statements
  filter_out <= output_register;
END rtl;
